home:
   path: /
   controller: App\Controller\ProduitController::produits

addProduit:
   path: /ajoutProduit
   controller: App\Controller\ProduitController::addProduit

produit:
  path: /produit/{id}
  controller: App\Controller\ProduitController::produit

panier:
  path: /panier
  controller: App\Controller\PanierController::panier

panierSuppr:
  path: /panierSuppr/{id}
  controller: App\Controller\PanierController::supprProduit

produitSuppr:
  path: /produit/Suppr/{id}
  controller: App\Controller\ProduitController::deleteProduit
